export const contractCategoryOptions: string[] = [
  "Apparel & Accessories",
  "Automotive & Powersports",
  "Automotive Electronics",
  "Baby",
  "Beauty",
  "Books",
  "Camera & Photo",
  "Cell Phones",
  "Consumer Electronics",
  "Electronics Accessories",
  "Indoor & Outdoor Furniture",
  "Decor",
  "Gourmet Food",
  "Grocery",
  "Health & Personal Care",
  "Home & Garden",
  "Industrial & Scientific",
  "Jewelry",
  "Kitchen",
  "Luggage & Travel Accessories",
  "Major Appliances",
  "Music",
  "Musical Instruments",
  "Office Products",
  "Outdoors",
  "Outdoor Power Tools",
  "Personal Computers",
  "Pet Supplies",
  "Plumbing Heating Cooling & Ventilation",
  "Shoes, Handbags & Sunglasses",
  "Software & Computer Video Games",
  "Sporting Goods",
  "Tires & Wheels",
  "Tools & Home Improvement",
  "Toys & Games",
  "Video & DVD",
  "Video Game Consoles",
  "Video Games",
  "Watches",
  "Everything Else"
];

export const seasonOptions: string[] = ["Jan-Sep", "Oct-Dec"];
